// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA19G8UN4QJL1y1G7mNjh7IAKrvnIgD8xc',
    appId: '1:1061033565145:web:c4eb26a23ff71e795097c8',
    messagingSenderId: '1061033565145',
    projectId: 'copper-f9e3b',
    authDomain: 'copper-f9e3b.firebaseapp.com',
    storageBucket: 'copper-f9e3b.appspot.com',
    measurementId: 'G-4JXNV9VP8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfixGZdyxeVyVn80NvHq6p4TLpkz2r3I',
    appId: '1:1061033565145:android:b147ddbe465b00bf5097c8',
    messagingSenderId: '1061033565145',
    projectId: 'copper-f9e3b',
    storageBucket: 'copper-f9e3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmXaD0VSyAW4qkWe6eoRfaYXsBMAVNSw',
    appId: '1:1061033565145:ios:b75036373aa9fc415097c8',
    messagingSenderId: '1061033565145',
    projectId: 'copper-f9e3b',
    storageBucket: 'copper-f9e3b.appspot.com',
    iosClientId: '1061033565145-q5trc06j0otcldfmdiurhmlogfmo9u29.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDatingApp',
  );
}
