// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKativQXZWY-ks7WFcIxndSiCjnfxhErI',
    appId: '1:863919874437:web:7563952a1f227f4b01a4ec',
    messagingSenderId: '863919874437',
    projectId: 'copper-f1097',
    authDomain: 'copper-f1097.firebaseapp.com',
    storageBucket: 'copper-f1097.appspot.com',
    measurementId: 'G-GZ8RZ8GJ4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5W3t77-aclgnBYfoswm_v3-7ArhWB1xI',
    appId: '1:863919874437:android:85d9ac83350be86101a4ec',
    messagingSenderId: '863919874437',
    projectId: 'copper-f1097',
    storageBucket: 'copper-f1097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0MWGq4YIDojIy9n9FX9TlUv7gzKG0iY',
    appId: '1:863919874437:ios:1b0e35896d0dd8cc01a4ec',
    messagingSenderId: '863919874437',
    projectId: 'copper-f1097',
    storageBucket: 'copper-f1097.appspot.com',
    iosClientId: '863919874437-16d108002foaefmfer7uedk6msbfl86s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDatingAppSeries',
  );
}
