// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO_fGjRS2zbnLen6a9MjD_sigLx8oqffo',
    appId: '1:999226414708:web:972635944cc2b226ee6321',
    messagingSenderId: '999226414708',
    projectId: 'copperapp-a3d58',
    authDomain: 'copperapp-a3d58.firebaseapp.com',
    storageBucket: 'copperapp-a3d58.appspot.com',
    measurementId: 'G-35BTXT3WSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY7kvo436QTWX40xJ29nyKTSOX-VRBeIE',
    appId: '1:999226414708:android:903b1cfb7861cf80ee6321',
    messagingSenderId: '999226414708',
    projectId: 'copperapp-a3d58',
    storageBucket: 'copperapp-a3d58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtXcRmd2Usv3Zb73c_EOq_LA-oQmwcfuY',
    appId: '1:999226414708:ios:4122b7f22a692b9dee6321',
    messagingSenderId: '999226414708',
    projectId: 'copperapp-a3d58',
    storageBucket: 'copperapp-a3d58.appspot.com',
    iosClientId: '999226414708-7l12b8rlqas84imrsdhihpe8abcbons0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDatingAppSeries',
  );
}
